### List

GET http://127.0.0.1:8000/api/examCategories
Accept: application/json

### Store

POST http://127.0.0.1:8000/api/examCategories
Accept: application/json
Content-Type: application/json

{
  "title": "Final-Exam",
  "class_name": "One",
  "section_name": "A",
}

### Show

GET http://127.0.0.1:8000/api/examCategories/
Accept: application/json

### Update

PUT http://127.0.0.1:8000/api/examCategories/
Accept: application/json
Content-Type: application/json

{
    "title": "45675756",
    "class_name": "Islam",
    "section_name": "suhana@gmail.com",
}

### Destroy

DELETE http://127.0.0.1:8000/api/examCategories/
Accept: application/json

