### List

GET http://127.0.0.1:8000/api/students
Accept: application/json

### Store

POST http://127.0.0.1:8000/api/students
Accept: application/json
Content-Type: application/json

{
  "first_name": "jannatul",
  "last_name": "lam",
  "email": "lam@gmail.com",
  "designation": "J.Software Engineer",
  "department": "Software",
  "password": "12345",
  "user_information": "etretert",
  "image": "dgfd.jpg",
  "gender": "female"
}

### Show

GET http://127.0.0.1:8000/api/students/9
Accept: application/json

### Update

PUT http://127.0.0.1:8000/api/students/9
Accept: application/json
Content-Type: application/json

{
  "first_name": "Jannatul Ferdaous",
  "last_name": "Lam",
  "email": "lam@gmail.com",
  "designation": "J.Software Engineer",
  "department": "Software",
  "password": "12345",
  "user_information": "etretert",
  "image": "dgfd.jpg",
  "gender": "female"
}

### Destroy

DELETE http://127.0.0.1:8000/api/students/9
Accept: application/json

