### List

GET http://127.0.0.1:8000/api/classRooms

Accept: application/json

### Store

POST http://127.0.0.1:8000/api/classRooms
Accept: application/json
Content-Type: application/json

{
    "class_room_name": "Class Room",
    "room_number": "201",
    "building_name": "Shapla Building",
    "area": "2025 m",
    "total_room": "12"
}

### Show

GET http://127.0.0.1:8000/api/classRooms/1
Accept: application/json

### Update

PUT http://127.0.0.1:8000/api/classRooms/1
Accept: application/json
Content-Type: application/json

{
    "class_room_name": "Class Room",
    "room_number": "201",
    "building_name": "Shapla Building",
    "area": "2025 m",
    "total_room": "13"
}

### Destroy

DELETE http://127.0.0.1:8000/api/classRooms/1
Accept: application/json

