### List

GET http://127.0.0.1:8000/api/marks
Accept: application/json

### Store

POST http://127.0.0.1:8000/api/marks
Accept: application/json
Content-Type: application/json

{
    "student_name": "Friha",
    "total_marks": "67",
    "grade_point": "4.22",
    "class_name": "One",
    "letter_grade": "B",
    "section": "B",
    "comment": "Need Inprovement"
}

### Show

GET http://127.0.0.1:8000/api/marks/1
Accept: application/json

### Update

PUT http://127.0.0.1:8000/api/marks/1
Accept: application/json
Content-Type: application/json

{
    "student_name": "Friha99",
    "total_marks": "67",
    "grade_point": "4.22",
    "class_name": "One",
    "letter_grade": "B",
    "section": "B",
    "comment": "Need Inprovement"
}

### Destroy

DELETE http://127.0.0.1:8000/api/marks/1
Accept: application/json

