### List

GET http://127.0.0.1:8000/api/offlineExams
Accept: application/json

### Store

POST http://127.0.0.1:8000/api/offlineExams
Accept: application/json
Content-Type: application/json

{
    "exam_name": "English",
    "paper": "I",
    "class_name": "Ten",
    "section": "A",
    "subject_code": "20011",
    "date_time": "10-12-23",
    "exam_start_time": "10:00",
    "exam_end_time": "1:00",
    "building_name": "Najrul Hall",
    "room_number": "219",
    "total_marks": "100"
}

### Show

GET http://127.0.0.1:8000/api/offlineExams/1
Accept: application/json

### Update

PUT http://127.0.0.1:8000/api/offlineExams/1
Accept: application/json
Content-Type: application/json

{
    "exam_name": "Bangla",
    "paper": "I",
    "class_name": "Ten",
    "section": "A",
    "subject_code": "20011",
    "date_time": "10-12-23",
    "exam_start_time": "10:00",
    "exam_end_time": "1:00",
    "building_name": "Najrul Hall",
    "room_number": "219",
    "total_marks": "100"
}

### Destroy

DELETE http://127.0.0.1:8000/api/offlineExams/1
Accept: application/json
