### List

GET http://127.0.0.1:8000/api/schools
Accept: application/json

### Store

POST http://127.0.0.1:8000/api/schools
Accept: application/json
Content-Type: application/json

{
  "title": "Ghatail Cantonment English School ",
  "email": "gcesc00@gmail.com",
  "phone": "09225",
  "address": "Shaheed Salahuddin Cantonment, Ghatail, Tangail.",
  "facebook_page": "gces.education",
  "status": "2"
}

### Show

GET http://127.0.0.1:8000/api/schools/2
Accept: application/json

### Update

PUT http://127.0.0.1:8000/api/schools/2
Accept: application/json
Content-Type: application/json

{
  "title": "Ghatail Cantonment English School ",
  "email": "gcesc00@gmail.com",
  "phone": "092256",
  "address": "Shaheed Salahuddin Cantonment, Ghatail, Tangail.",
  "facebook_page": "gces.education",
  "status": "2"
}
