### List

GET http://127.0.0.1:8000/api/schoolMagazines

Accept: application/json

### Store

POST http://127.0.0.1:8000/api/schoolMagazines
Accept: application/json
Content-Type: application/json

{
    "magazine_name": "Class Room"
}

### Show

GET http://127.0.0.1:8000/api/schoolMagazines/1
Accept: application/json

### Update

PUT http://127.0.0.1:8000/api/schoolMagazines/1
Accept: application/json
Content-Type: application/json

{
    "magazine_name": "Class Room"
}

### Destroy

DELETE http://127.0.0.1:8000/api/schoolMagazines/1
Accept: application/json

