### List

GET http://127.0.0.1:8000/api/students
Accept: application/json

### Store

POST http://127.0.0.1:8000/api/students
Accept: application/json
Content-Type: application/json

{
  "first_name": "Labonno",
  "last_name": "Chowdhury",
  "email": "labonno@gmail.com",
  "designation": "Engineer",
  "department": "EEE",
  "password": "123",
  "user_information": "user_information",
  "image": "dgfd.jpg",
  "gender": "female"
}

### Show

GET http://127.0.0.1:8000/api/students/13
Accept: application/json

### Update

PUT http://127.0.0.1:8000/api/students/13
Accept: application/json
Content-Type: application/json

{
    "first_name": "Morium",
    "last_name": "Islam",
    "email": "morium@gmail.com",
    "designation": "Software Engineer",
    "department": "Software",
    "password": "123",
    "user_information": "user_information",
    "image": "dgfd.jpg",
    "gender": "female"
}

### Destroy

DELETE http://127.0.0.1:8000/api/students/9
Accept: application/json

