### List

GET http://127.0.0.1:8000/api/subjects
Accept: application/json

### Store

POST http://127.0.0.1:8000/api/subjects
Accept: application/json
Content-Type: application/json

{
    "subject_name": "English",
    "class": "Ten",
    "subject_code": "20011",
    "paper": "1st"
}

### Show

GET http://127.0.0.1:8000/api/subjects/1
Accept: application/json

### Update

PUT http://127.0.0.1:8000/api/subjects/1
Accept: application/json
Content-Type: application/json

{
    "subject_name": "English",
    "class": "Nine",
    "subject_code": "20011",
    "paper": "1st"
}

### Destroy

DELETE http://127.0.0.1:8000/api/subjects/1
Accept: application/json

